FROM python:3.11-slim

WORKDIR /app

RUN apt-get update
RUN apt-get install -y ffmpeg git

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7860

CMD ["python", "run.py"]
